import { StyleSheet } from "react-native";

export default StyleSheet.create({
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  container: {
    padding: 24,
    backgroundColor: "#fff",
    flexGrow: 1,
    alignItems: "center",
  },
  section: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 8,
    marginBottom: 18,
    width: "100%",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  item: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    justifyContent: "space-between",
  },
  itemText: {
    fontSize: 16,
    color: "#222",
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#00b4d8",
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 18,
    width: "100%",
    justifyContent: "space-between",
  },
  shareText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#eee",
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 18,
    width: "100%",
    justifyContent: "space-between",
    backgroundColor: "#fff",
  },
  logoutText: {
    color: "#e74c3c",
    fontSize: 16,
    fontWeight: "bold",
  },
});